top_srcdir   = /root/download/startuppack/httpd-2.2.8
top_builddir = /root/download/startuppack/httpd-2.2.8
srcdir       = /root/download/startuppack/httpd-2.2.8/modules/mappers
builddir     = /root/download/startuppack/httpd-2.2.8/modules/mappers
VPATH        = /root/download/startuppack/httpd-2.2.8/modules/mappers

include $(top_srcdir)/build/special.mk

