top_srcdir   = /root/download/startuppack/httpd-2.2.8
top_builddir = /root/download/startuppack/httpd-2.2.8
srcdir       = /root/download/startuppack/httpd-2.2.8/modules/metadata
builddir     = /root/download/startuppack/httpd-2.2.8/modules/metadata
VPATH        = /root/download/startuppack/httpd-2.2.8/modules/metadata

include $(top_srcdir)/build/special.mk

