top_srcdir   = /root/download/startuppack/httpd-2.2.8
top_builddir = /root/download/startuppack/httpd-2.2.8
srcdir       = /root/download/startuppack/httpd-2.2.8/modules/loggers
builddir     = /root/download/startuppack/httpd-2.2.8/modules/loggers
VPATH        = /root/download/startuppack/httpd-2.2.8/modules/loggers

include $(top_srcdir)/build/special.mk

