top_srcdir   = /root/download/startuppack/httpd-2.2.8
top_builddir = /root/download/startuppack/httpd-2.2.8
srcdir       = /root/download/startuppack/httpd-2.2.8/server/mpm/worker
builddir     = /root/download/startuppack/httpd-2.2.8/server/mpm/worker
VPATH        = /root/download/startuppack/httpd-2.2.8/server/mpm/worker

LTLIBRARY_NAME    = libworker.la
LTLIBRARY_SOURCES = worker.c fdqueue.c pod.c

include $(top_srcdir)/build/ltlib.mk
