top_srcdir   = /root/download/startuppack/httpd-2.2.8
top_builddir = /root/download/startuppack/httpd-2.2.8
srcdir       = /root/download/startuppack/httpd-2.2.8/modules/generators
builddir     = /root/download/startuppack/httpd-2.2.8/modules/generators
VPATH        = /root/download/startuppack/httpd-2.2.8/modules/generators

include $(top_srcdir)/build/special.mk

