top_srcdir   = /root/download/startuppack/httpd-2.2.8
top_builddir = /root/download/startuppack/httpd-2.2.8
srcdir       = /root/download/startuppack/httpd-2.2.8/modules/echo
builddir     = /root/download/startuppack/httpd-2.2.8/modules/echo
VPATH        = /root/download/startuppack/httpd-2.2.8/modules/echo

include $(top_srcdir)/build/special.mk

