top_srcdir   = /root/download/startuppack/httpd-2.2.8
top_builddir = /root/download/startuppack/httpd-2.2.8
srcdir       = /root/download/startuppack/httpd-2.2.8/modules/filters
builddir     = /root/download/startuppack/httpd-2.2.8/modules/filters
VPATH        = /root/download/startuppack/httpd-2.2.8/modules/filters

include $(top_srcdir)/build/special.mk

