top_srcdir   = /root/download/startuppack/httpd-2.2.8
top_builddir = /root/download/startuppack/httpd-2.2.8
srcdir       = /root/download/startuppack/httpd-2.2.8/modules/aaa
builddir     = /root/download/startuppack/httpd-2.2.8/modules/aaa
VPATH        = /root/download/startuppack/httpd-2.2.8/modules/aaa

include $(top_srcdir)/build/special.mk

