top_srcdir   = /root/download/startuppack/httpd-2.2.8
top_builddir = /root/download/startuppack/httpd-2.2.8
srcdir       = /root/download/startuppack/httpd-2.2.8/modules/cache
builddir     = /root/download/startuppack/httpd-2.2.8/modules/cache
VPATH        = /root/download/startuppack/httpd-2.2.8/modules/cache

include $(top_srcdir)/build/special.mk

