top_srcdir   = /root/download/startuppack/httpd-2.2.8
top_builddir = /root/download/startuppack/httpd-2.2.8
srcdir       = /root/download/startuppack/httpd-2.2.8/os
builddir     = /root/download/startuppack/httpd-2.2.8/os
VPATH        = /root/download/startuppack/httpd-2.2.8/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
