top_srcdir   = /root/download/startuppack/httpd-2.2.8
top_builddir = /root/download/startuppack/httpd-2.2.8
srcdir       = /root/download/startuppack/httpd-2.2.8/modules/http
builddir     = /root/download/startuppack/httpd-2.2.8/modules/http
VPATH        = /root/download/startuppack/httpd-2.2.8/modules/http

include $(top_srcdir)/build/special.mk

