top_srcdir   = /root/download/startuppack/httpd-2.2.8
top_builddir = /root/download/startuppack/httpd-2.2.8
srcdir       = /root/download/startuppack/httpd-2.2.8/server/mpm
builddir     = /root/download/startuppack/httpd-2.2.8/server/mpm
VPATH        = /root/download/startuppack/httpd-2.2.8/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
